name: Create and publish a Docker image to Github Packages

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Setup Environments
        id: envs
        run: |
          IPTVCHECKER_LATEST_TAG=$(git describe --tags --abbrev=0)
          DOCKER_IMAGE=${{ github.repository }}

          echo "RELEASE_VERSION=${GITHUB_REF#refs}"
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${IPTVCHECKER_LATEST_TAG}"

          echo "IPTVCHECKER_LATEST_TAG:${IPTVCHECKER_LATEST_TAG}"
          echo ::set-output name=tags::${TAGS}
          mkdir iptv-checker && cp dockerfile iptv-checker/dockerfile
          git clone https://github.com/zhimin-dev/iptv-checker-rs.git
          git clone https://github.com/zhimin-dev/iptv-checker-web.git
      - name: Setup Docker Buildx Command
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: iptv-checker/dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.envs.outputs.tags }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
          registry: ${{ env.REGISTRY }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
