name: Rust

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # or just on button clicked

permissions:
  contents: write

jobs:
  build_release:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-musleabihf
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout iptv-checker-rs
        uses: actions/checkout@v4
        with:
          repository: zhimin-dev/iptv-checker-rs
          path: iptv-checker-rs

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cross
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./iptv-checker-rs
        run: cargo install cross

      - name: Build - windows
        if: matrix.os == 'windows-latest'
        working-directory: ./iptv-checker-rs
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build - linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./iptv-checker-rs
        run: cross build --release --target ${{ matrix.target }}

      - name: Build - macos
        if: matrix.os == 'macos-latest'
        working-directory: ./iptv-checker-rs
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        working-directory: ./iptv-checker-rs
        run: strip "target/${{ matrix.target }}/release/iptv-checker-rs"

      - name: Build archive
        shell: bash
        working-directory: ./iptv-checker-rs
        run: |
          # Replace with the name of your binary
          binary_name="iptv-checker-rs"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi
          mv web $dirname
          mkdir -p $dirname/static/input
          mkdir -p $dirname/static/out
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./iptv-checker-rs/${{ env.ASSET }}
